### ISSUE TITLE
在python的例子中，char2num函数转换的'0'跟'Z'的结果一样？

### ISSUE THREAD

**Issue by wax8280** [skyduy/zfverify#1]
def char2num(char):
    t = ord(char)
    return (lambda x: x - 48 if x <= 57 else x - 87 if x <= 110 else x - 88)(t)

'0'的ASCII码是48，'Z'的是90。这不，'0'跟'Z'的结果都是3吗？

**Comment by skyduy** [comment]
@wax8280 
0 的 ASCII码为48，满足x <= 57，执行x - 48，返回0。
z 的 ASCII码为122，执行x - 88，返回34。
